---
name: practical-06
break: true
indent: 4
---

src/main/java/practicalsix:
    PizzaParty.java:
        ConfirmFileExists
        CountSingleLineComments --language Java --count 4
        MatchFileFragment --fragment "{Your Name Here}" --count 0 --exact
        MatchFileFragment --fragment "TODO" --count 0 --exact
        MatchFileFragment --fragment "= new Fraction(" --count 2
        MatchFileFragment --fragment ".getNumer()" --count 2 --exact
        MatchFileFragment --fragment ".getDenom()" --count 2 --exact
        MatchFileFragment --fragment ".getDecimalValue()" --count 1 --exact

src/main/java/practicalsix:
    Fraction.java:
        ConfirmFileExists
        MatchFileFragment --fragment "{Your Name Here}" --count 0 --exact
        MatchFileFragment --fragment "TODO" --count 0 --exact
        MatchFileFragment --fragment "public double getDecimalValue() {" --count 1 --exact
        MatchFileRegex --regex "(\()?double(\))?" --count 2
        
ExecuteCommand --command "gradle build"
ExecuteCommand --command "gradle run -q --console plain run"
MatchCommandFragment --command "gradle run -q --console plain run" --fragment "3/12" --count 1 --exact
MatchCommandFragment --command "gradle run -q --console plain run" --fragment "0.25" --count 1 --exact